version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recipes-lambdas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g7duuwb0ctb8"
s3_prefix = "recipes-lambdas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaLayerArn=\"arn:aws:lambda:us-east-1:706927318824:layer:pymongolayer:1, arn:aws:lambda:us-east-1:706927318824:layer:inflectlayer:1, arn:aws:lambda:us-east-1:706927318824:layer:pandas_layer:1, arn:aws:lambda:us-east-1:706927318824:layer:nltk_layer:3\" InfraStackName=\"recipes-infrastructure\" SecretManagerName=\"docdbrecipesaccess\""
